# Auto-generated symbolic field expressions
import sympy as sp

# Common sub-expressions
x0 = Pow(Symbol('y', real=True), Integer(5))
x1 = Mul(Symbol('a_2_4'), Symbol('s', real=True))
x2 = Mul(Rational(1, 10), Symbol('a_3_3'))
x3 = Mul(Symbol('s', real=True), Symbol('x', real=True))
x4 = Pow(Symbol('y', real=True), Integer(4))
x5 = Mul(Symbol('b_1_4'), Symbol('s', real=True))
x6 = Mul(Rational(1, 4), Symbol('b_2_3'))
x7 = Mul(Rational(1, 12), Symbol('b_3_2'))
x8 = Pow(Symbol('s', real=True), Integer(2))
x9 = Mul(Rational(1, 8), Symbol('b_3_3'))
x10 = Pow(Symbol('x', real=True), Integer(2))
x11 = Pow(Symbol('s', real=True), Integer(3))
x12 = Mul(Symbol('b_3_4'), Symbol('x11'))
x13 = Mul(Rational(1, 2), Symbol('x10'))
x14 = Mul(Symbol('s', real=True), Symbol('x13'))
x15 = Pow(Symbol('y', real=True), Integer(2))
x16 = Mul(Symbol('b_1_2'), Symbol('s', real=True))
x17 = Mul(Rational(1, 2), Symbol('x', real=True))
x18 = Mul(Symbol('b_1_3'), Symbol('x8'))
x19 = Mul(Symbol('b_1_4'), Symbol('x11'))
x20 = Mul(Rational(3, 2), Symbol('x8'))
x21 = Pow(Symbol('y', real=True), Integer(3))
x22 = Mul(Symbol('a_1_3'), Symbol('x', real=True))
x23 = Mul(Symbol('bs_3'), Symbol('s', real=True))
x24 = Mul(Symbol('a_2_2'), Symbol('s', real=True))
x25 = Mul(Rational(1, 6), Symbol('a_3_1'))
x26 = Mul(Integer(4), Symbol('a_1_4'))
x27 = Mul(Rational(1, 3), Symbol('a_3_2'))
x28 = Mul(Rational(1, 2), Symbol('x8'))
x29 = Mul(Symbol('a_2_4'), Symbol('x11'))
x30 = Pow(Symbol('x', real=True), Integer(3))
x31 = Mul(Rational(1, 6), Symbol('x30'))
x32 = Mul(Integer(2), Symbol('x8'))
x33 = Mul(Integer(2), Symbol('x10'))
x34 = Mul(Symbol('x17'), Symbol('x8'))
x35 = Mul(Symbol('s', real=True), Symbol('x30'))
x36 = Mul(Rational(2, 3), Symbol('a_3_4'))
x37 = Mul(Symbol('x11'), Symbol('x36'))
x38 = Mul(Integer(3), Symbol('x8'))
x39 = Mul(Integer(4), Symbol('x11'))
x40 = Mul(Symbol('a_1_4'), Symbol('x39'))
x41 = Pow(Symbol('s', real=True), Integer(4))
x42 = Add(Symbol('bs_0'), Mul(Symbol('bs_1'), Symbol('s', real=True)), Mul(Symbol('bs_2'), Symbol('x8')), Mul(Symbol('bs_3'), Symbol('x11')), Mul(Symbol('bs_4'), Symbol('x41')))
x43 = Add(Symbol('b_1_0'), Mul(Symbol('b_1_1'), Symbol('s', real=True)), Mul(Symbol('b_1_2'), Symbol('x8')), Mul(Symbol('b_1_3'), Symbol('x11')), Mul(Symbol('b_1_4'), Symbol('x41')))
x44 = Mul(Symbol('b_2_1'), Symbol('s', real=True))
x45 = Mul(Symbol('b_2_2'), Symbol('x8'))
x46 = Mul(Symbol('b_2_3'), Symbol('x11'))
x47 = Mul(Symbol('b_2_4'), Symbol('x41'))
x48 = Add(Mul(Rational(1, 2), Symbol('b_2_0')), Mul(Rational(1, 2), Symbol('x44')), Mul(Rational(1, 2), Symbol('x45')), Mul(Rational(1, 2), Symbol('x46')), Mul(Rational(1, 2), Symbol('x47')))
x49 = Mul(Symbol('b_3_1'), Symbol('s', real=True))
x50 = Mul(Symbol('b_3_2'), Symbol('x8'))
x51 = Mul(Symbol('b_3_3'), Symbol('x11'))
x52 = Mul(Symbol('b_3_4'), Symbol('x41'))
x53 = Mul(Symbol('a_2_4'), Symbol('x', real=True))
x54 = Mul(Symbol('a_3_4'), Symbol('x8'))
x55 = Mul(Symbol('a_1_3'), Symbol('s', real=True))
x56 = Mul(Rational(1, 3), Symbol('x', real=True))
x57 = Mul(Symbol('a_3_1'), Symbol('s', real=True))
x58 = Mul(Symbol('a_3_2'), Symbol('x8'))
x59 = Mul(Symbol('a_3_3'), Symbol('x11'))
x60 = Mul(Symbol('a_3_4'), Symbol('x41'))
x61 = Mul(Symbol('a_2_1'), Symbol('s', real=True))
x62 = Mul(Symbol('a_2_2'), Symbol('x8'))
x63 = Mul(Symbol('a_2_3'), Symbol('x11'))
x64 = Mul(Symbol('a_2_4'), Symbol('x41'))
x65 = Add(Symbol('a_1_0'), Mul(Symbol('a_1_1'), Symbol('s', real=True)), Mul(Symbol('a_1_2'), Symbol('x8')), Mul(Symbol('a_1_3'), Symbol('x11')), Mul(Symbol('a_1_4'), Symbol('x41')))
x66 = Add(Symbol('a_2_0'), Symbol('x61'), Symbol('x62'), Symbol('x63'), Symbol('x64'))
x67 = Add(Symbol('b_2_0'), Symbol('x44'), Symbol('x45'), Symbol('x46'), Symbol('x47'))
x68 = Add(Symbol('a_3_0'), Symbol('x57'), Symbol('x58'), Symbol('x59'), Symbol('x60'))
x69 = Mul(Integer(6), Symbol('x8'))
x70 = Add(Symbol('a_1_2'), Mul(Symbol('a_1_4'), Symbol('x69')), Mul(Integer(3), Symbol('x55')))
x71 = Mul(Rational(1, 2), Symbol('x15'))
x72 = Mul(Integer(3), Symbol('s', real=True))
x73 = Add(Symbol('b_2_2'), Mul(Symbol('b_2_3'), Symbol('x72')), Mul(Symbol('b_2_4'), Symbol('x69')))
x74 = Add(Symbol('a_3_2'), Mul(Symbol('a_3_3'), Symbol('x72')), Mul(Integer(6), Symbol('x54')))
x75 = Add(Symbol('b_3_0'), Symbol('x49'), Symbol('x50'), Symbol('x51'), Symbol('x52'))
x76 = Mul(Symbol('x', real=True), Symbol('y', real=True))
x77 = Add(Symbol('a_2_2'), Mul(Symbol('a_2_3'), Symbol('x72')), Mul(Symbol('a_2_4'), Symbol('x69')))
x78 = Mul(Symbol('x', real=True), Symbol('x15'))
x79 = Mul(Symbol('x13'), Symbol('x15'))
x80 = Add(Symbol('b_3_2'), Mul(Symbol('b_3_3'), Symbol('x72')), Mul(Symbol('b_3_4'), Symbol('x69')))
x81 = Mul(Integer(4), Symbol('bs_4'))
x82 = Mul(Integer(2), Symbol('s', real=True))
x83 = Mul(Rational(2, 3), Symbol('x21'))
x84 = Mul(Symbol('x', real=True), Symbol('x21'))
x85 = Add(Symbol('a_2_1'), Mul(Symbol('a_2_3'), Symbol('x38')), Mul(Integer(2), Symbol('x24')), Mul(Integer(4), Symbol('x29')))
x86 = Add(Symbol('a_2_3'), Mul(Integer(4), Symbol('x1')))
x87 = Add(Symbol('b_3_1'), Mul(Symbol('b_3_2'), Symbol('x82')), Mul(Symbol('b_3_3'), Symbol('x38')), Mul(Integer(4), Symbol('x12')))
x88 = Add(Symbol('a_3_1'), Mul(Symbol('a_3_2'), Symbol('x82')), Mul(Symbol('a_3_3'), Symbol('x38')), Mul(Symbol('a_3_4'), Symbol('x39')))
x89 = Mul(Integer(4), Symbol('s', real=True))
x90 = Add(Symbol('a_3_3'), Mul(Symbol('a_3_4'), Symbol('x89')))

# Reduced expressions
symbolic_Ax = Add(Mul(Integer(-1), Symbol('x0'), Add(Mul(Rational(1, 10), Symbol('a_2_3')), Mul(Rational(2, 5), Symbol('a_3_4'), Symbol('x3')), Mul(Rational(1, 5), Symbol('bs_4')), Mul(Symbol('x', real=True), Symbol('x2')), Mul(Rational(2, 5), Symbol('x1')))), Mul(Integer(-1), Symbol('x15'), Add(Mul(Rational(1, 2), Symbol('b_1_1')), Mul(Symbol('b_2_1'), Symbol('x17')), Mul(Symbol('b_2_2'), Symbol('x3')), Mul(Symbol('b_2_3'), Symbol('x', real=True), Symbol('x20')), Mul(Integer(2), Symbol('b_2_4'), Symbol('x', real=True), Symbol('x11')), Mul(Rational(1, 4), Symbol('b_3_1'), Symbol('x10')), Mul(Symbol('b_3_2'), Symbol('x14')), Mul(Rational(3, 4), Symbol('b_3_3'), Symbol('x10'), Symbol('x8')), Mul(Symbol('x10'), Symbol('x12')), Symbol('x16'), Mul(Rational(3, 2), Symbol('x18')), Mul(Integer(2), Symbol('x19')))), Mul(Integer(-1), Symbol('x21'), Add(Mul(Integer(-1), Rational(1, 6), Symbol('a_2_1')), Mul(Integer(-1), Symbol('a_2_3'), Symbol('x13')), Mul(Integer(-1), Symbol('a_2_3'), Symbol('x28')), Mul(Integer(-1), Symbol('a_3_3'), Symbol('x31')), Mul(Integer(-1), Symbol('a_3_3'), Symbol('x34')), Mul(Integer(-1), Rational(1, 3), Symbol('bs_2')), Mul(Integer(-1), Symbol('bs_4'), Symbol('x32')), Mul(Integer(-1), Symbol('x', real=True), Symbol('x25')), Mul(Integer(-1), Symbol('x', real=True), Symbol('x37')), Mul(Integer(-1), Symbol('x1'), Symbol('x33')), Mul(Integer(-1), Symbol('x22')), Mul(Integer(-1), Symbol('x23')), Mul(Integer(-1), Rational(1, 3), Symbol('x24')), Mul(Integer(-1), Symbol('x26'), Symbol('x3')), Mul(Integer(-1), Symbol('x27'), Symbol('x3')), Mul(Integer(-1), Rational(2, 3), Symbol('x29')), Mul(Integer(-1), Symbol('x35'), Symbol('x36')))), Mul(Integer(-1), Symbol('x4'), Add(Mul(Integer(-1), Rational(1, 4), Symbol('b_1_3')), Mul(Integer(-1), Symbol('b_2_4'), Symbol('x3')), Mul(Integer(-1), Rational(1, 24), Symbol('b_3_1')), Mul(Integer(-1), Symbol('b_3_4'), Symbol('x14')), Mul(Integer(-1), Symbol('s', real=True), Symbol('x7')), Mul(Integer(-1), Symbol('x', real=True), Symbol('x6')), Mul(Integer(-1), Symbol('x10'), Symbol('x9')), Mul(Integer(-1), Rational(1, 6), Symbol('x12')), Mul(Integer(-1), Symbol('x5')), Mul(Integer(-1), Symbol('x8'), Symbol('x9')))), Mul(Integer(-1), Symbol('y', real=True), Add(Mul(Symbol('a_1_1'), Symbol('x', real=True)), Mul(Integer(2), Symbol('a_1_2'), Symbol('x3')), Mul(Symbol('a_2_1'), Symbol('x13')), Mul(Symbol('a_2_3'), Symbol('x10'), Symbol('x20')), Mul(Symbol('a_3_3'), Symbol('x28'), Symbol('x30')), Mul(Symbol('x', real=True), Symbol('x40')), Mul(Symbol('x10'), Symbol('x24')), Mul(Symbol('x22'), Symbol('x38')), Mul(Symbol('x25'), Symbol('x30')), Mul(Symbol('x27'), Symbol('x35')), Mul(Symbol('x29'), Symbol('x33')), Mul(Symbol('x30'), Symbol('x37')), Symbol('x42'))))
symbolic_Ay = Integer(0)
symbolic_As = Add(Mul(Integer(-1), Symbol('x', real=True), Symbol('x43')), Mul(Symbol('x0'), Add(Mul(Rational(1, 5), Symbol('a_1_4')), Mul(Rational(1, 30), Symbol('a_3_2')), Mul(Rational(1, 10), Symbol('a_3_4'), Symbol('x10')), Mul(Symbol('s', real=True), Symbol('x2')), Mul(Rational(1, 5), Symbol('x53')), Mul(Rational(1, 5), Symbol('x54')))), Mul(Integer(-1), Symbol('x10'), Symbol('x48')), Mul(Symbol('x15'), Add(Mul(Symbol('b_3_0'), Symbol('x17')), Mul(Symbol('x17'), Symbol('x49')), Mul(Symbol('x17'), Symbol('x50')), Mul(Symbol('x17'), Symbol('x51')), Mul(Symbol('x17'), Symbol('x52')), Symbol('x48'))), Mul(Symbol('x21'), Add(Mul(Integer(-1), Rational(1, 3), Symbol('a_1_2')), Mul(Integer(-1), Symbol('a_1_4'), Symbol('x32')), Mul(Integer(-1), Symbol('a_2_2'), Symbol('x56')), Mul(Integer(-1), Symbol('a_2_3'), Symbol('x3')), Mul(Integer(-1), Rational(1, 6), Symbol('a_3_0')), Mul(Integer(-1), Rational(1, 6), Symbol('a_3_2'), Symbol('x10')), Mul(Integer(-1), Symbol('a_3_3'), Symbol('x14')), Mul(Integer(-1), Symbol('x10'), Symbol('x54')), Mul(Integer(-1), Symbol('x32'), Symbol('x53')), Mul(Integer(-1), Symbol('x55')), Mul(Integer(-1), Rational(1, 6), Symbol('x57')), Mul(Integer(-1), Rational(1, 6), Symbol('x58')), Mul(Integer(-1), Rational(1, 6), Symbol('x59')), Mul(Integer(-1), Rational(1, 6), Symbol('x60')))), Mul(Integer(-1), Symbol('x30'), Add(Mul(Rational(1, 6), Symbol('b_3_0')), Mul(Rational(1, 6), Symbol('x49')), Mul(Rational(1, 6), Symbol('x50')), Mul(Rational(1, 6), Symbol('x51')), Mul(Rational(1, 6), Symbol('x52')))), Mul(Symbol('x4'), Add(Mul(Integer(-1), Rational(1, 12), Symbol('b_2_2')), Mul(Integer(-1), Symbol('b_2_4'), Symbol('x28')), Mul(Integer(-1), Rational(1, 4), Symbol('b_3_3'), Symbol('x3')), Mul(Integer(-1), Symbol('b_3_4'), Symbol('x34')), Mul(Integer(-1), Symbol('s', real=True), Symbol('x6')), Mul(Integer(-1), Symbol('x', real=True), Symbol('x7')))), Mul(Symbol('y', real=True), Add(Mul(Symbol('a_2_0'), Symbol('x', real=True)), Mul(Symbol('a_3_0'), Symbol('x13')), Mul(Symbol('x', real=True), Symbol('x61')), Mul(Symbol('x', real=True), Symbol('x62')), Mul(Symbol('x', real=True), Symbol('x63')), Mul(Symbol('x', real=True), Symbol('x64')), Mul(Symbol('x13'), Symbol('x57')), Mul(Symbol('x13'), Symbol('x58')), Mul(Symbol('x13'), Symbol('x59')), Mul(Symbol('x13'), Symbol('x60')), Symbol('x65'))))
symbolic_Bx = Add(Mul(Symbol('a_1_4'), Symbol('x4')), Mul(Symbol('a_3_4'), Symbol('x13'), Symbol('x4')), Mul(Symbol('x', real=True), Symbol('x66')), Mul(Symbol('x13'), Symbol('x68')), Mul(Integer(-1), Symbol('x15'), Symbol('x70')), Mul(Integer(-1), Symbol('x21'), Symbol('x56'), Symbol('x80')), Mul(Integer(-1), Rational(1, 3), Symbol('x21'), Symbol('x73')), Mul(Symbol('x4'), Symbol('x53')), Mul(Rational(1, 6), Symbol('x4'), Symbol('x74')), Symbol('x65'), Mul(Symbol('x67'), Symbol('y', real=True)), Mul(Integer(-1), Symbol('x68'), Symbol('x71')), Mul(Integer(-1), Symbol('x74'), Symbol('x79')), Mul(Symbol('x75'), Symbol('x76')), Mul(Integer(-1), Symbol('x77'), Symbol('x78')))
symbolic_By = Add(Mul(Symbol('a_2_4'), Symbol('x21'), Symbol('x33')), Mul(Symbol('a_3_4'), Symbol('x30'), Symbol('x83')), Mul(Symbol('x', real=True), Symbol('x67')), Mul(Symbol('x', real=True), Symbol('x74'), Symbol('x83')), Mul(Integer(-1), Symbol('x10'), Symbol('x77'), Symbol('y', real=True)), Mul(Symbol('x13'), Symbol('x75')), Mul(Integer(-1), Symbol('x15'), Add(Symbol('b_1_2'), Mul(Symbol('b_1_3'), Symbol('x72')), Mul(Symbol('b_1_4'), Symbol('x69')))), Mul(Symbol('x21'), Add(Symbol('bs_3'), Mul(Symbol('s', real=True), Symbol('x81')))), Mul(Symbol('x26'), Symbol('x84')), Mul(Integer(-1), Rational(1, 3), Symbol('x30'), Symbol('x74'), Symbol('y', real=True)), Symbol('x43'), Mul(Integer(-1), Symbol('x66'), Symbol('y', real=True)), Mul(Integer(-1), Symbol('x68'), Symbol('x76')), Mul(Integer(-1), Integer(2), Symbol('x70'), Symbol('x76')), Mul(Integer(-1), Symbol('x71'), Symbol('x75')), Mul(Integer(-1), Symbol('x73'), Symbol('x78')), Mul(Symbol('x77'), Symbol('x83')), Mul(Integer(-1), Symbol('x79'), Symbol('x80')), Mul(Integer(-1), Symbol('y', real=True), Add(Symbol('bs_1'), Mul(Symbol('bs_2'), Symbol('x82')), Mul(Symbol('bs_3'), Symbol('x38')), Mul(Symbol('x11'), Symbol('x81')))))
symbolic_Bs = Add(Mul(Symbol('bs_4'), Symbol('x4')), Mul(Symbol('x', real=True), Add(Symbol('a_1_1'), Mul(Symbol('a_1_2'), Symbol('x82')), Mul(Symbol('a_1_3'), Symbol('x38')), Symbol('x40'))), Mul(Integer(-1), Rational(3, 2), Symbol('x10'), Symbol('x15'), Symbol('x86')), Mul(Integer(-1), Symbol('x13'), Symbol('x21'), Add(Symbol('b_3_3'), Mul(Symbol('b_3_4'), Symbol('x89')))), Mul(Symbol('x13'), Symbol('x85')), Mul(Symbol('x13'), Symbol('x87'), Symbol('y', real=True)), Mul(Integer(-1), Symbol('x15'), Symbol('x17'), Symbol('x88')), Mul(Integer(-1), Symbol('x15'), Add(Symbol('bs_2'), Mul(Symbol('bs_4'), Symbol('x69')), Mul(Integer(3), Symbol('x23')))), Mul(Symbol('x17'), Symbol('x4'), Symbol('x90')), Mul(Integer(-1), Rational(1, 6), Symbol('x21'), Symbol('x87')), Mul(Integer(-1), Symbol('x21'), Add(Symbol('b_1_3'), Mul(Integer(4), Symbol('x5')))), Mul(Integer(-1), Symbol('x30'), Symbol('x71'), Symbol('x90')), Mul(Symbol('x31'), Symbol('x88')), Mul(Rational(1, 2), Symbol('x4'), Symbol('x86')), Symbol('x42'), Mul(Integer(-1), Symbol('x71'), Symbol('x85')), Mul(Symbol('x76'), Add(Symbol('b_2_1'), Mul(Symbol('b_2_2'), Symbol('x82')), Mul(Symbol('b_2_3'), Symbol('x38')), Mul(Symbol('b_2_4'), Symbol('x39')))), Mul(Integer(-1), Integer(3), Symbol('x78'), Add(Symbol('a_1_3'), Mul(Symbol('a_1_4'), Symbol('x89')))), Mul(Integer(-1), Symbol('x84'), Add(Symbol('b_2_3'), Mul(Symbol('b_2_4'), Symbol('x89')))), Mul(Symbol('y', real=True), Add(Symbol('b_1_1'), Mul(Integer(2), Symbol('x16')), Mul(Integer(3), Symbol('x18')), Mul(Integer(4), Symbol('x19')))))

