# TODO: Keep splines + Sinusoids
#       Wiggler generates data about the splines and sinusoids
# TODO: Add class "WigglerSlice" (based on Gianni's MyWiggler) that can contain a single bpmeth instance.
#       Receives a1, a2, a3, b1, b2, b3, bs and so on to generate one instance of bpmeth
#       Contains the starting position of the element, and x y offsets
# TODO: The entire wiggler should be stored in another object which can combine the results into one object
#       Receives the bpmeth instances and stores them in one object
#       Needs to be able to return the magnetic field for any s
#       Builds a line with the slices
# TODO: If I'm done with this before Tuesday, I'd like to get rid of the sinusoids altogether, just splines.

from __future__ import annotations

from tkinter.messagebox import ABORT

import numpy as np
import pandas as pd
import scipy as sc
import sympy as sp
import xtrack as xt

import bpmeth as bp
import time
from bpmeth import poly_fit
from scipy.signal import find_peaks
from scipy.optimize import curve_fit
from numpy.polynomial import Polynomial
import matplotlib.pyplot as plt
from line_profiler import profile

# ================================ Main class ================================

class WigglerFieldFitter:

    def __init__(
            self,
            file_path,
            xy_point=(0, 0),
            dx=0.001,
            dy=0.001,
            ds=0.001,
            peak_window=(100, 2100),
            n_modes=6,
            poly_pieces=[[15, 15], [15, 15], [15, 15]],
            deg=0,
            filter_params=None,
    ):

        self.file_path = file_path
        self.xy_point = xy_point
        self.dx, self.dy, self.ds = dx, dy, ds
        self.peak_window = peak_window
        self.n_modes = n_modes

        # NOTE: Filter noise is now only used for the right tails, because those are noisy.
        # We can add a more general functionality later.
        self.filter_params = filter_params

        self.shapes = {
            "Bx": {"n_pieces_L": poly_pieces[0][0], "n_pieces_R": poly_pieces[0][1]},
            "By": {"n_pieces_L": poly_pieces[1][0], "n_pieces_R": poly_pieces[1][1]},
            "Bs": {"n_pieces_L": poly_pieces[2][0], "n_pieces_R": poly_pieces[2][1]},
        }

        self.df = None
        self.s_full = None
        self.length = None
        self.deg = deg

        # Dictionary that holds a list of borders for each field
        self.borders_idx  = {"Bx": None, "By": None, "Bs": None}
        self.poly_borders = {"Bx": [], "By": [], "Bs": []}

        # Data dictionaries
        # raw_data holds the data from the file
        # fit_data holds the data generated by fitting
        self.raw_data = {}
        self.fit_data = {}
        self.fit_pars = {}
        for ii in range(self.deg + 1):
            self.raw_data[ii] = {"Bx": None, "By": None, "Bs": None}
            self.fit_data[ii] = {"Bx": None, "By": None, "Bs": None}
            self.fit_pars[ii] = {"Bx": {}, "By": {}, "Bs": {}}

        self.Bs_tol = 10e-3
        self.Bs_fit = None

    # PUBLIC
    # Setter method that calls all the other methods to arrive at a fit.
    def set(self):
        self._parse_to_dataframe()
        self.select_xy()
        if self.filter_params != None:
            self._filter_noise()
        self._find_regions()
        self._fit_sinusoids()
        self._fit_edges()



    ####################################################################################################################
    # EVALUATION FUNCTIONS
    ####################################################################################################################

    # PRIVATE
    # This function evaluates a sum of (co)sines at the given x values.
    # The parameters are given as a flat list, where each mode has three parameters:
    #  - Amplitude of the cosine term
    #  - Amplitude of the sine term
    #  - Wave number
    # Thus, for n modes, the parameter list has length 3*n.
    @staticmethod
    def _sinusoid(x, *params):
        # Define the output array
        y = np.zeros_like(x, dtype=np.float64)

        # The range depends on the number of sinusoids there are present in the function.
        # B_x is best approximated with two, whereas B_y only needs one.
        # Note the integer division by 3, because each mode has three parameters.
        for A1, A2, k in zip(params[::3], params[1::3], params[2::3]):
            # General sinusoidal part is a linear combination of cosine and sine.
            # This is equivalent to a single function with a phase-offset, but more numerically stable.
            y += A1 * np.cos(k * x) + A2 * np.sin(k * x)

        if (len(params) % 3) == 1:
            y += params[-1]

        return y

    # PRIVATE
    # Polynomials, which coefficients are determined by the boundary conditions and integral over the interval.
    @staticmethod
    def _poly(x0, x1, coeffs):
        c1, c2, c3, c4, c5 = coeffs
        L = x1 - x0
        t = np.polynomial.Polynomial([-x0 / L, 1 / L])

        # basis functions on [0,1]
        b1_coeffs = [1, 0, -18, 32, -15]
        b2_coeffs = [0, 1, -4.5, 6, -2.5]
        b3_coeffs = [0, 0, -12, 28, -15]
        b4_coeffs = [0, 0, 1.5, -4, 2.5]
        b5_coeffs = [0, 0, 30, -60, 30]
        b1_poly = np.polynomial.Polynomial(b1_coeffs)
        b2_poly = np.polynomial.Polynomial(b2_coeffs)
        b3_poly = np.polynomial.Polynomial(b3_coeffs)
        b4_poly = np.polynomial.Polynomial(b4_coeffs)
        b5_poly = np.polynomial.Polynomial(b5_coeffs)

        # combine with correct scaling for derivatives/integral
        poly_t = c1 * b1_poly + L * c2 * b2_poly + c3 * b3_poly + L * c4 * b4_poly + (c5 / L) * b5_poly
        poly_x = poly_t(t)
        return poly_x

    # Workflow:
    # 1. Define the interval [x0, x1]: We know this from the slices.
    # 2. Compute the function value and derivative at the sinusoidal side (analytically), gives c_3 and c_4 (left side) or c_1 and c_2 (right side).
    # 3. Compute the function value and derivative at the "data side" (numerically), gives c_1 and c_2 (left side) or c_3 and c_4 (right side).
    # 4. Compute the integral over the interval (numerically), gives c_5.
    # 5. This immediately gives the polynomial coefficients for that slice.

    ####################################################################################################################
    # IDENTIFYING REGIONS AND SETTING BORDERS IN DATA CLASSES
    ####################################################################################################################

    # PRIVATE
    # This method reads the data from the file and stores it in a pandas DataFrame.
    def _parse_to_dataframe(self) -> None:
        df = pd.read_csv(
            self.file_path, sep=r"\s+", header=None, names=["X", "Y", "Z", "Bx", "By", "Bs"]
        )
        df.set_index(["X", "Y", "Z"], inplace=True)
        self.df = df

    # PUBLIC
    # This method selects the data at the specified (x,y) point and stores it in the fields dictionary.
    # It is made public so that the user can change the (x,y) point and re-select the data without re-parsing the file.
    def select_xy(self):
        subset = self.df.xs(self.xy_point, level=["X", "Y"]).sort_index()

        self.s_full = subset.index.to_numpy() * self.ds
        self.length = self.s_full[-1] - self.s_full[0]

        # Store the raw data for each field.

        for field in ["Bx", "By", "Bs"]:
            for der_order in range(self.deg+1):
                if der_order == 0:
                    self.raw_data[der_order][field] = subset[field].to_numpy()
                    self.fit_data[der_order][field] = np.zeros_like(self.raw_data[der_order][field])
                else:
                    self._fit_transverse_polynomials(degree=self.deg, der=der_order)
                    self.fit_data[der_order][field] = np.zeros_like(self.raw_data[der_order][field])

                if (self.raw_data[der_order]["Bs"] is not None and max(self.raw_data[der_order]["Bs"]) /
                        min(max(self.raw_data[der_order]["Bx"]),
                        max(self.raw_data[der_order]["By"])) < self.Bs_tol):
                    self.Bs_fit = False
                    self.fit_pars[der_order]["Bs"]["sines"] = [0.0]
                    self.fit_pars[der_order]["Bs"]["edge_L"] = [0.0]
                    self.fit_pars[der_order]["Bs"]["edge_R"] = [0.0]


    @staticmethod
    def find_sign_change_indices(y, eps=0.0):
        """
        Indices i where y[i] and y[i+1] have opposite signs.
        Exact zeros are not counted as crossings.

        eps > 0 treats |y| <= eps as 0 to add a small hysteresis.
        """
        y = np.asarray(y, float)
        if eps > 0:
            y = np.where(np.abs(y) <= eps, 0.0, y)

        y0 = y[:-1]
        y1 = y[1:]

        valid = ~np.isnan(y0) & ~np.isnan(y1)
        crossings = valid & (y0 * y1 < 0)  # strict sign change
        return np.flatnonzero(crossings)

    # PRIVATE
    # This method first finds the peaks and valleys in the data for Bx and By
    # Then, it combines them into one array for the extrema of Bx and By
    # Finally, it sets the borders_idx attribute of the FieldChannel objects for Bx and By
    def _find_regions(self):
        w_left = self.peak_window[0]
        w_right = self.peak_window[1]

        for field in ["Bx", "By", "Bs"]:
            field_peaks = find_peaks(self.raw_data[0][field])[0]
            field_valleys = find_peaks(-self.raw_data[0][field])[0]
            field_peaks = field_peaks[np.logical_and(field_peaks > w_left, field_peaks < w_right)]
            field_valleys = field_valleys[np.logical_and(field_valleys > w_left, field_valleys < w_right)]
            field_extrema = np.sort(np.concatenate((field_peaks, field_valleys)))
            self.borders_idx[field] = [field_extrema[4], field_extrema[-4]]


    # PRIVATE
    # This is an impromptu noise-filter.
    # Will probably need to be improved later.
    # For now, it only filters noise from the right tail of the data, because that's where the noise is present.
    def _filter_noise(self):
        from scipy.signal import savgol_filter
        from scipy.signal import medfilt

        left_idx = self.filter_params[0]
        right_idx = self.filter_params[1]
        kernel_size = self.filter_params[2]
        window_length = self.filter_params[3]
        polyorder = self.filter_params[4]

        for field in ["Bx", "By", "Bs"]:

            # Because Bs is very noisy, we also filter the left tail.
            # This is not necessary for Bx and By, because their left tails are not noisy.
            if field == "Bs":
                tail = slice(None, left_idx)
                m = medfilt(self.raw_data[field][tail].copy(), kernel_size=kernel_size)
                y_sm = savgol_filter(m, window_length=window_length, polyorder=polyorder)
                self.raw_data[field][tail] = y_sm

                tail = slice(right_idx, None)
                m = medfilt(self.raw_data[field][tail].copy(), kernel_size=kernel_size)  # kernel_size must be odd
                y_sm = savgol_filter(m, window_length=window_length, polyorder=polyorder)
                self.raw_data[field][tail] = y_sm

            tail = slice(right_idx, None)
            m = medfilt(self.raw_data[field][tail].copy(), kernel_size=kernel_size)  # kernel_size must be odd
            y_sm = savgol_filter(m, window_length=window_length, polyorder=polyorder)
            self.raw_data[field][tail] = y_sm



    ####################################################################################################################
    # SINUSOID FITTING
    ####################################################################################################################

    # PRIVATE
    # This function finds the amplitudes and frequencies of the (co)sines present in the data.
    @staticmethod
    def _find_modes(x, y, dx, n_modes):
        # Fourier Transform and frequencies
        fft = sc.fft.fft(y)
        fftfreq = sc.fft.fftfreq(len(x), dx)

        # Only keep positive frequencies
        fft = fft[fftfreq > 0]
        fftfreq = fftfreq[fftfreq > 0]

        # Find peaks in the magnitude spectrum
        peaks = find_peaks(np.abs(fft))[0]

        # Order peaks by magnitude, descending
        order = np.argsort(np.abs(fft[peaks]))[::-1]
        peaks = peaks[order][:n_modes]

        # Extract amplitudes and frequencies in the same order
        amplitudes = fft[peaks]
        cos_amps = 2 * dx * amplitudes.real
        sin_amps = -2 * dx * amplitudes.imag
        k_values = 2 * np.pi * fftfreq[peaks]

        return cos_amps, sin_amps, k_values

    # PRIVATE
    # This method fits sinusoids to the data in the regions defined by borders_idx.
    # The fitted parameters are stored in the fit_pars attribute.
    # The fitted data is stored in the fit_data attribute.
    # It uses the _find_modes function to get initial guesses for the parameters.
    def _fit_sinusoids(self, fun=True):
        if self.Bs_fit:
            fields = ["Bx", "By", "Bs"]
        else:
            fields = ["Bx", "By"]

        for field in fields:
            for der_order in range(self.deg+1):
                sin_slice = slice(self.borders_idx[field][0], self.borders_idx[field][1])
                s_reg = self.s_full[sin_slice]

                if fun:
                    field_reg = self.raw_data[der_order][field][sin_slice]
                else:
                    field_reg = self.trans_der2[field][sin_slice]

                cos_amps, sin_amps, k_modes = self._find_modes(s_reg, field_reg, self.ds, self.n_modes)

                p0 = np.zeros(self.n_modes * 3 + 1)
                p0[-1] = float(np.mean(field_reg))  # DC guess

                for ii in range(self.n_modes):
                    p0[3 * ii + 0] = cos_amps[ii]
                    p0[3 * ii + 1] = sin_amps[ii]
                    p0[3 * ii + 2] = k_modes[ii]

                popt, pcov = curve_fit(self._sinusoid, s_reg, field_reg, p0=p0)

                self.fit_pars[der_order][field]["sines"] = popt
                self.fit_data[der_order][field][sin_slice] = self._sinusoid(s_reg, *popt)

    ####################################################################################################################
    # PIECEWISE POLYNOMIAL FITTING
    ####################################################################################################################

    # PRIVATE
    # Takes the fit parameters from the sinusoidal fit
    # and computes the boundary conditions for the polynomial fits
    # fL, fR are the function values at the left and right boundaries
    # dL, dR are the first derivatives at the left and right boundaries
    # ddL, ddR are the second derivatives at the left and right boundaries
    def _boundary_from_sine(self, field, s_mid, der_order=0):
        xL, xR = s_mid[0] - self.ds, s_mid[-1] + self.ds
        fL = fR = dL = dR = ddL = ddR = 0.0

        params = self.fit_pars[der_order][field]["sines"]
        for Ac, As, k in zip(params[::3], params[1::3], params[2::3]):
            fL += Ac * np.cos(k * xL) + As * np.sin(k * xL)
            fR += Ac * np.cos(k * xR) + As * np.sin(k * xR)
            dL += k * (As * np.cos(k * xL) - Ac * np.sin(k * xL))
            dR += k * (As * np.cos(k * xR) - Ac * np.sin(k * xR))

        if (len(params) % 3) == 1:
            c0 = params[-1]
            fL += c0
            fR += c0

        return np.array([fL, fR, dL, dR], dtype=float)

    # PRIVATE
    # This method computes the boundary conditions from a previously fitted polynomial.
    # xL, xR are the left and right boundaries of the new region.
    # dp and ddp are the first and second derivatives of the polynomial.
    def _boundary_from_poly(self, s_prev, poly):
        xL, xR = s_prev[0] - self.ds, s_prev[-1] + self.ds
        dp = poly.deriv()
        return np.array([poly(xL), poly(xR), dp(xL), dp(xR)], dtype=float)

    # PRIVATE
    # This slices a region into num_regions slices of (approximately) equal size.
    @staticmethod
    def _balanced_slices(n, num_regions):
        base, rem = n // num_regions, n % num_regions
        slices, start = [], 0
        for i in range(num_regions):
            end = start + base + (1 if i < rem else 0)
            if end > start:
                slices.append(slice(start, end))
            start = end
        return slices

    def _fit_poly_side(self, field, s_region, b_region, s_mid, num_slices, left_side, der_order):
        slices = self._balanced_slices(len(s_region), num_slices)
        # fit order: first piece next to the center, then outward
        slices_proc = list(reversed(slices)) if left_side else slices

        fit_reg = np.zeros_like(s_region, dtype=float)
        pieces = []
        prev_poly = None
        prev_s = None

        for ix, s in enumerate(slices_proc):
            s_this, b_this = s_region[s], b_region[s]
            integral_this = sc.integrate.trapezoid(b_this, s_this)
            if ix == 0:
                boundaries = self._boundary_from_sine(field, s_mid, der_order)
            else:
                boundaries = self._boundary_from_poly(prev_s, prev_poly)

            if left_side:
                dbL = (-3 * b_this[0] + 4 * b_this[1] - b_this[2]) / (2 * self.ds)
                coeffs = (b_this[0], dbL, boundaries[0], boundaries[2], integral_this)
            else:
                dbR = (3 * b_this[-1] - 4 * b_this[-2] + b_this[-3]) / (2 * self.ds)
                coeffs = (boundaries[1], boundaries[3], b_this[-1], dbR, integral_this)
            # ----------------------------------------------------------

            x0 = float(s_this[0])
            x1 = float(s_this[-1])
            poly = self._poly(x0, x1, coeffs)
            fit_reg[s] = poly(s_this)
            pieces.append((s.start, poly))
            prev_poly, prev_s = poly, s_this

        # borders in strictly increasing s on this side
        slices_ord = sorted(slices, key=lambda sl: sl.stop)
        borders = [float(s_region[0])] + [float(s_region[sl.stop - 1]) for sl in slices_ord]
        return fit_reg, pieces, borders

    def _fit_edges(self):
        if self.Bs_fit:
            fields = ["Bx", "By", "Bs"]
        else:
            fields = ["Bx", "By"]
        for field in fields:
            for der_order in range(self.deg+1):
                # center region slice and grid
                i0, i1 = self.borders_idx[field]
                s_mid = self.s_full[i0:i1]

                # tails
                s_left = self.s_full[:i0]
                s_right = self.s_full[i1:]
                b_left = self.raw_data[der_order][field][:i0]
                b_right = self.raw_data[der_order][field][i1:]

                # degrees + number of chained pieces per side (configurable)
                nL = int(self.shapes[field]["n_pieces_L"])
                nR = int(self.shapes[field]["n_pieces_R"])
                fitL, piecesL, bordersL = self._fit_poly_side(field, s_left, b_left, s_mid, nL, left_side=True,
                                                              der_order=der_order)
                self.fit_data[der_order][field][:i0] = fitL
                fitR, piecesR, bordersR = self._fit_poly_side(field, s_right, b_right, s_mid, nR, left_side=False,
                                                              der_order=der_order)
                self.fit_data[der_order][field][i1:] = fitR

                # after computing fitL/piecesL and fitR/piecesR:
                self.fit_data[der_order][field][:i0] = fitL
                self.fit_data[der_order][field][i1:] = fitR

                # NEW: store coefficients (ascending-power) for exporter
                self.fit_pars[der_order][field]["edge_L"] = [p[1].coef for p in piecesL]  # order: near-center -> far-left
                self.fit_pars[der_order][field]["edge_R"] = [p[1].coef for p in piecesR]  # order: near-center -> far-right

                # existing border assembly (kept)
                self.poly_borders[field] = bordersL[:-1] + [float(self.s_full[i0]), float(self.s_full[i1])] + bordersR[1:]

    ####################################################################################################################
    # TRANSVERSE GRADIENTS
    ####################################################################################################################

    # PRIVATE
    # This method extracts the data at (x,y) = (-1,0), (0,0), (1,0) and fits parabolas to these points.
    # This is done because bpmeth needs the derivatives w.r.t. x at each point.
    # The first derivatives are zero, but can be extracted nevertheless.

    def _fit_transverse_polynomials(self, points=[-1, 0, 1], degree=2, der=0):
        """
        Fits transverse polynomials of arbitrary degree through specified points and returns the der-th derivative at x=0.

        Parameters
        ----------
        points : list of int or float
            The transverse x positions (in multiples of dx) to use for fitting.
            Must have at least (degree + 1) entries.
        degree : int
            Degree of the polynomial to fit.
        der : int
            The order of the derivative to return (0 = value, 1 = first derivative, etc.)
        Returns
        -------
        dict
            Dictionary with keys "Bx", "By", "Bs" and values as arrays of the der-th derivative at x=0.
        """

        subsets = {px: self.df.xs((px, 0), level=["X", "Y"]).sort_index() for px in points}
        polys = {"Bx": None, "By": None, "Bs": None}
        derivs = {"Bx": None, "By": None, "Bs": None}

        for field in ["Bx", "By", "Bs"]:
            x = [p * self.dx for p in points]
            n = len(subsets[points[0]][field])
            polys[field] = np.zeros((n, degree + 1))
            derivs[field] = np.zeros(n)

            for i in range(n):
                y = [subsets[px][field].to_numpy()[i] for px in points]
                coeffs = np.polyfit(x, y, degree)
                polys[field][i, :] = coeffs
                # Compute the der-th derivative at x=0
                d_coeffs = np.polyder(coeffs, m=der)
                # Evaluate at x=0
                derivs[field][i] = np.polyval(d_coeffs, 0)

            # Optionally store the result for later use
            self.raw_data[der][field] = derivs[field]

        self._fitted_polynomials = polys
        return derivs

    ####################################################################################################################
    # STRINGS FOR BPMETH
    ####################################################################################################################
    # TODO: This whole section can go. We no longer need strings.
    def _num(self, x, p=12):
        return f"{float(x):.{p}g}"

    def _poly_to_sympy(self, coeffs, p=12):
        import sympy as sp
        s = sp.Symbol('s')
        expr = sp.Integer(0)
        for n, c in enumerate(coeffs):
            if c == 0:
                continue
            expr += sp.N(c, p) * s**n
        return sp.sympify(expr)

    def _sines_to_sympy(self, params, p=12):
        import sympy as sp
        s = sp.Symbol('s')
        expr = sp.Integer(0)
        if params is None or len(params) == 0:
            return expr
        for Ac, As, k in zip(params[0::3], params[1::3], params[2::3]):
            expr += sp.N(Ac, p) * sp.cos(sp.N(k, p) * s) + sp.N(As, p) * sp.sin(sp.N(k, p) * s)
        if (len(params) % 3) == 1:
            expr += sp.N(params[-1], p)
        return sp.sympify(expr)

    def _export_piecewise_segments(self, field="By", precision=12, der=0):
        i0, i1 = self.borders_idx[field]
        s = self.s_full
        s_min, s_max = float(s[0]), float(s[-1])

        pars = self.fit_pars[der][field]

        # ---- Defensive: if Bs is not fitted or borders invalid ----
        if field == "Bs" and (not self.Bs_fit or i1 <= i0 or not pars):
            return [(s_min, s_max, sp.Float(0))]
        s = self.s_full
        sL, sR = s[:i0], s[i1:]
        s_min, s_max = float(s[0]), float(s[-1])
        center_right = float(s[i1 - 1]) if i1 > i0 else float(s[i0])

        pars = self.fit_pars[der][field]
        L_coeffs = list(pars.get("edge_L", []))
        R_coeffs = list(pars.get("edge_R", []))
        L_coeffs = list(reversed(L_coeffs))

        nL, nR = len(L_coeffs), len(R_coeffs)
        bordersL, bordersR = [], []

        if nL > 0 and len(sL) > 0:
            slL = self._balanced_slices(len(sL), nL)
            bordersL = [float(sL[sl.stop - 1]) for sl in slL]
        if nR > 0 and len(sR) > 0:
            slR = self._balanced_slices(len(sR), nR)
            bordersR = [float(sR[sl.stop - 1]) for sl in slR]

        segments = []  # each entry will be (start, end, expr_str)

        # left pieces
        prev = s_min
        for j, cf in enumerate(L_coeffs):
            end = bordersL[j]
            expr = self._poly_to_sympy(cf, precision)
            segments.append((prev, end, expr))
            prev = end

        # center sine
        sine_params = pars.get("sines", [])
        if i1 > i0 and len(sine_params):
            start_c = bordersL[-1] if bordersL else float(s[i0 - 1]) if i0 > 0 else s_min
            expr_c = self._sines_to_sympy(sine_params, precision)
            segments.append((start_c, center_right, expr_c))

        # right pieces
        prev = center_right
        for j, cf in enumerate(R_coeffs):
            end = bordersR[j]
            expr = self._poly_to_sympy(cf, precision)
            segments.append((prev, end, expr))
            prev = end

        return segments

    ####################################################################################################################
    # PLOTTING
    ####################################################################################################################

    @staticmethod
    def _integrate(data, ds):
        return sc.integrate.cumulative_trapezoid(data, initial=0) * ds

    def plot_integrated_fields(self):
        fig1, (ax1, ax2, ax3) = plt.subplots(3, figsize=(10, 4), constrained_layout=True)

        Bx_int_raw = self._integrate(self.raw_data[0]["Bx"], self.ds)
        By_int_raw = self._integrate(self.raw_data[0]["By"], self.ds)
        Bs_int_raw = self._integrate(self.raw_data[0]["Bs"], self.ds)

        Bx_int_fit = self._integrate(self.fit_data[0]["Bx"], self.ds)
        By_int_fit = self._integrate(self.fit_data[0]["By"], self.ds)
        Bs_int_fit = self._integrate(self.fit_data[0]["Bs"], self.ds)

        ax1.plot(self.s_full, Bx_int_raw, label='Raw Data')
        ax1.plot(self.s_full, Bx_int_fit, label='Fit', linestyle='--')
        ax2.plot(self.s_full, By_int_raw, label='Raw Data')
        ax2.plot(self.s_full, By_int_fit, label='Fit', linestyle='--')
        ax3.plot(self.s_full, Bs_int_raw, label='Raw Data')
        ax3.plot(self.s_full, Bs_int_fit, label='Fit', linestyle='--')

        # Add vertical lines at different positions for each subplot
        for field in ["Bx", "By", "Bs"]:
            for idx in self.borders_idx[field]:
                ax = {"Bx": ax1, "By": ax2, "Bs": ax3}[field]
                ax.axvline(x=self.s_full[idx], color='k', linestyle='--', linewidth=1)

        ax1.set_title(f"Integrated Magnetic Field at (X, Y) = {self.xy_point}")
        ax1.set_ylabel(r"Integrated Horizontal Field, $\int B_x \, ds$ [T·m]")
        ax2.set_ylabel(r"Integrated Vertical Field, $\int B_y \, ds$ [T·m]")
        ax3.set_ylabel(r"Integrated Longitudinal Field, $\int B_s \, ds$ [T·m]")
        ax3.set_xlabel(r"Longitudinal Position, $s$ [m]")

        ax1.legend(loc="lower right")
        ax2.legend(loc="lower right")
        ax3.legend(loc="upper right")

        # Turn on the grids.
        ax1.grid()
        ax2.grid()
        ax3.grid()

        plt.show()

    # PUBLIC
    # Plot the data against the fit.
    def plot_fields(self, der=0):
        fig1, (ax1, ax2, ax3) = plt.subplots(3, figsize=(10, 4), constrained_layout=True)

        ax1.plot(self.s_full, self.raw_data[der]["Bx"])
        ax1.plot(self.s_full, self.fit_data[der]["Bx"])
        ax2.plot(self.s_full, self.raw_data[der]["By"])
        ax2.plot(self.s_full, self.fit_data[der]["By"])
        ax3.plot(self.s_full, self.raw_data[der]["Bs"])
        ax3.plot(self.s_full, self.fit_data[der]["Bs"])

        # Add vertical lines at different positions for each subplot
        for field in ["Bx", "By", "Bs"]:
            for idx in self.borders_idx[field]:
                ax = {"Bx": ax1, "By": ax2, "Bs": ax3}[field]
                ax.axvline(x=self.s_full[idx], color='k', linestyle='--', linewidth=1)

        if der == 2:
            x_label = r"$\frac{d^2 B_x}{d x^2}$"
            y_label = r"$\frac{d^2 B_y}{d y^2}$"
            s_label = r"$\frac{d^2 B_s}{d x^2}$"
        elif der == 1:
            x_label = r"$\frac{d B_x}{d x}$"
            y_label = r"$\frac{d B_y}{d y}$"
            s_label = r"$\frac{d B_s}{d x}$"
        else:
            x_label = r"$B_x$"
            y_label = r"$B_y$"
            s_label = r"$B_s$"

        ax1.set_title(f"Magnetic Field at (X, Y) = {self.xy_point}")
        ax1.set_ylabel(f"Horizontal Field, {x_label} [T]")
        ax2.set_ylabel(f"Vertical Field, {y_label} [T]")
        ax3.set_ylabel(f"Longitudinal Field, {s_label} [T]")
        ax3.set_xlabel(r"Longitudinal Position, $s$ [m]")

        ax1.legend([f"{x_label} Data", f"{x_label} Fit"], loc="lower right")
        ax2.legend([f"{y_label} Data", f"{y_label} Fit"], loc="lower right")
        ax3.legend([f"{s_label} Data", f"{s_label} Fit"], loc="upper right")

        # Turn on the grids.
        ax1.grid()
        ax2.grid()
        ax3.grid()

        plt.show()

# This class takes the a_n, b_n and b_s coefficients from the WigglerFieldFitter
# It generates the magnetic field functions using bpmeth's GeneralVectorPotential, which it stores as attributes
# It is meant to only store one single segment

# Workflow for next step:
# - Let GeneralVectorPotential generate from a symbolic expression
# - Use GeneralVectorPotential.get_Bfield(lambdify=False) to get Bx, By, Bs functions
# - Use GeneralVectorPotential.get_A() to get Ax, Ay, As functions
#   - These functions are still symbolic expressions
#   - The shape of these functions can be either a sinusoid or a polynomial, depending on the parameters from WigglerFieldFitter
# - These expressions can be "recycled" by copying them and substituting the coefficients for a particular segment in them
# - After this whole process, we lambdify (or numbafy)? Is supposedly faster.

# TODO:
# - Generic symbolic expressions are part of WigglerFull
# -
class WigglerSegment:
    def __init__(self, a_list, b_list, bs, s0=0, length=0, x0=0, y0=0, curv=0):
        self.s0 = s0
        self.length = length
        self.x0 = x0
        self.y0 = y0
        self.scale = 1.0

        # TODO: These tuples might not be needed here.
        # TODO: Will look into where they can be put instead.
        self.bs = bs
        self.a = tuple(a_list)
        self.b = tuple(b_list)
        self.curv = curv

        # bpmeth objects / expressions / callables (constructed lazily)
        self.wiggler_map = None

        self.Bxexpr = None
        self.Byexpr = None
        self.Bsexpr = None
        self.Bxfun = None
        self.Byfun = None
        self.Bsfun = None

        self.Axexpr = None
        self.Ayexpr = None
        self.Asexpr = None
        self.Axfun = None
        self.Ayfun = None
        self.Asfun = None

    def get_field(self, x, y, s):
        return (self.scale * self.Bxfun(x - self.x0, y - self.y0, s),
                self.scale * self.Byfun(x - self.x0, y - self.y0, s),
                self.scale * self.Bsfun(x - self.x0, y - self.y0, s))

    # Order of arguments: (x, y, s). Vectorized.
    def get_vector_potential(self, x, y, s):
        Ax = self.scale * self.Axfun(x - self.x0, y - self.y0, s)
        Ay = self.scale * self.Ayfun(x - self.x0, y - self.y0, s)
        As = self.scale * self.Asfun(x - self.x0, y - self.y0, s)
        return Ax, Ay, As


class WigglerFull:
    def __init__(self, WigglerFieldFitter):
        self.field_fitter = WigglerFieldFitter
        self.segments = []
        self.integrator = []
        self.n_slices = 0
        self.env = None
        self.wiggler_line = None

        self._set_generic_expr()
        #self.set_segments()

    def _set_generic_expr(self):
        n_modes = self.field_fitter.n_modes
        n_ders = self.field_fitter.deg
        s = sp.symbols("s")
        curv = 0

        # Define symbols
        Aa_syms = {(i, j): sp.Symbol(f"Aa{i}_{j}") for i in range(1, n_modes + 1) for j in range(1, n_ders + 2)}
        Ba_syms = {(i, j): sp.Symbol(f"Ba{i}_{j}") for i in range(1, n_modes + 1) for j in range(1, n_ders + 2)}
        ka_syms = {(i, j): sp.Symbol(f"ka{i}_{j}") for i in range(1, n_modes + 1) for j in range(1, n_ders + 2)}

        Ab_syms = {(i, j): sp.Symbol(f"Ab{i}_{j}") for i in range(1, n_modes + 1) for j in range(1, n_ders + 2)}
        Bb_syms = {(i, j): sp.Symbol(f"Bb{i}_{j}") for i in range(1, n_modes + 1) for j in range(1, n_ders + 2)}
        kb_syms = {(i, j): sp.Symbol(f"kb{i}_{j}") for i in range(1, n_modes + 1) for j in range(1, n_ders + 2)}

        a_sine_exprs = tuple(
            sum(Aa_syms[i, j] * sp.cos(ka_syms[i, j] * s) + Ba_syms[i, j] * sp.sin(ka_syms[i, j] * s)
                for i in range(1, n_modes + 1))
            for j in range(1, n_ders + 2)
        )

        b_sine_exprs = tuple(
            sum(
                Ab_syms[i, j] * sp.cos(kb_syms[i, j] * s) + Bb_syms[i, j] * sp.sin(kb_syms[i, j] * s)
                for i in range(1, n_modes + 1)
            )
            for j in range(1, n_ders + 2)
        )

        print("a_sine_expr:", a_sine_exprs)
        print("b_sine_expr:", b_sine_exprs)

        deg_poly = 4
        # create per-derivative polynomial coefficient symbols and expressions (degree 4 -> 5 terms)
        a_p_syms = {j: sp.symbols(f"a_{j}_0:{deg_poly+1}") for j in range(1, n_ders + 2)}
        b_p_syms = {j: sp.symbols(f"b_{j}_0:{deg_poly+1}") for j in range(1, n_ders + 2)}
        a_poly_exprs = tuple(
            sum(coef * s**i for i, coef in enumerate(a_p_syms[j]))
            for j in range(1, n_ders + 2)
        )
        b_poly_exprs = tuple(
            sum(coef * s**i for i, coef in enumerate(b_p_syms[j]))
            for j in range(1, n_ders + 2)
        )

        print("a_poly_exprs:", a_poly_exprs)
        print("b_poly_exprs:", b_poly_exprs)

        # Changed GeneralVectorPotential to accept expressions with free parameters such as Ac_i, As_i, k_i.
        # Pass the sympy expressions as strings (bpmeth/bp accepts string expressions)
        # self.generic_sine_A = (Ax, Ay, As)
        # self.generic_sine_B = (Bx, By, Bs)
        # Likewise for generic_poly_A and generic_poly_B
        generic_sine_bpmeth = bp.GeneralVectorPotential(hs=f"{curv}", a=a_sine_exprs, b=b_sine_exprs)
        self.generic_sine_B = generic_sine_bpmeth.get_Bfield(lambdify=False)
        self.generic_sine_A = generic_sine_bpmeth.get_A()

        generic_poly_bpmeth = bp.GeneralVectorPotential(hs=f"{curv}", a=a_poly_exprs, b=b_poly_exprs)
        self.generic_poly_B = generic_poly_bpmeth.get_Bfield(lambdify=False)
        self.generic_poly_A = generic_poly_bpmeth.get_A()

    def set_segments(self):
        N = self.field_fitter.deg + 1  # number of derivatives per field

        # --- Export all derivative data ---
        segs_Bx = [self.field_fitter._export_piecewise_segments("Bx", der=n) for n in range(N)]
        segs_By = [self.field_fitter._export_piecewise_segments("By", der=n) for n in range(N)]
        segs_Bs = self.field_fitter._export_piecewise_segments("Bs", der=0)


        # --- Build unified segmentation grid from all fields ---
        boundaries = set()
        for seg_list in segs_Bx + segs_By + [segs_Bs]:
            for s0, s1, _ in seg_list:
                boundaries.add(s0)
                boundaries.add(s1)
        s_grid = sorted(boundaries)

        # --- Create WigglerSegments based on unified grid ---
        self.segments = []
        for i in range(len(s_grid) - 1):
            s_start = s_grid[i]
            s_end = s_grid[i + 1]
            ell_j = s_end - s_start
            s_mid = 0.5 * (s_start + s_end)

            # Helper to get the segment value that covers s_mid
            def find_value(segments):
                for s0, s1, val in segments:
                    if s0 <= s_mid <= s1:
                        return val
                # fallback: last valid
                return segments[-1][2]

            # Collect all derivatives for Bx, By
            A_j = [find_value(segs_Bx[n]) for n in range(N)]
            B_j = [find_value(segs_By[n]) for n in range(N)]
            b_sj = find_value(segs_Bs)

            seg = WigglerSegment(
                a_list=A_j,
                b_list=B_j,
                bs=b_sj,
                s0=s_start,
                length=ell_j,
                x0=0.0,
                y0=0.0,
                curv=0.0,
            )
            self.segments.append(seg)
            self._lambdify_segment_from_generic(seg, deg_poly=4, n_modes=self.field_fitter.n_modes)

    def set_integrator(self, n_slices=1000, n_steps = 1000):
        if self.segments == []:
            self.set_segments()

        self.n_slices = n_slices
        l_wig = self.field_fitter.length
        s_start = self.field_fitter.s_full[0]
        s_end   = self.field_fitter.s_full[-1]

        s_cuts = np.linspace(s_start, s_end, n_slices + 1)
        #s_mid = 0.5 * (s_cuts[:-1] + s_cuts[1:])
        for ii in range(n_slices):
            wig = xt.BorisSpatialIntegrator(fieldmap_callable=self.get_field, s_start=s_cuts[ii], s_end=s_cuts[ii + 1],
                                            n_steps=np.round(n_steps / n_slices).astype(int),
                                            verbose=True)
            self.integrator.append(wig)

    def get_line(self):
        if self.integrator == []:
            self.set_integrator()

        self.env = xt.Environment()

        for ii in range(self.n_slices):
            self.env.elements[f'wigslice_{ii}'] = self.integrator[ii]
        self.wiggler_line = self.env.new_line(components=['wigslice_' + str(ii) for ii in range(self.n_slices)])
        return self.wiggler_line

    def correctors(self, particle_ref):
        start_time = time.time()
        if self.wiggler_line is None:
            self.get_line()

        self.wiggler_line.particle_ref = particle_ref

        self.env['k0l_corr1'] = 0.
        self.env['k0l_corr2'] = 0.
        self.env['k0l_corr3'] = 0.
        self.env['k0l_corr4'] = 0.
        self.env['k0sl_corr1'] = 0.
        self.env['k0sl_corr2'] = 0.
        self.env['k0sl_corr3'] = 0.
        self.env['k0sl_corr4'] = 0.
        self.env['on_wig_corr'] = 1.0

        self.env.new('corr1', xt.Multipole, knl=['on_wig_corr * k0l_corr1'], ksl=['on_wig_corr * k0sl_corr1'])
        self.env.new('corr2', xt.Multipole, knl=['on_wig_corr * k0l_corr2'], ksl=['on_wig_corr * k0sl_corr2'])
        self.env.new('corr3', xt.Multipole, knl=['on_wig_corr * k0l_corr3'], ksl=['on_wig_corr * k0sl_corr3'])
        self.env.new('corr4', xt.Multipole, knl=['on_wig_corr * k0l_corr4'], ksl=['on_wig_corr * k0sl_corr4'])

        l_wig = self.field_fitter.length

        self.wiggler_line.insert([
            self.env.place('corr1', at=0.02),
            self.env.place('corr2', at=0.1),
            self.env.place('corr3', at=l_wig - 0.1),
            self.env.place('corr4', at=l_wig - 0.02),
        ], s_tol=5e-3
        )

        # To compute the kicks
        opt = self.wiggler_line.match(
            solve=False,
            betx=0, bety=0,
            only_orbit=True,
            include_collective=True,
            vary=xt.VaryList(['k0l_corr1', 'k0sl_corr1',
                              'k0l_corr2', 'k0sl_corr2',
                              'k0l_corr3', 'k0sl_corr3',
                              'k0l_corr4', 'k0sl_corr4',
                              ], step=1e-6),
            targets=[
                xt.TargetSet(x=0, px=0, y=0, py=0., at=xt.END),
                xt.TargetSet(x=0., y=0, at='wigslice_167'),
                xt.TargetSet(x=0., y=0, at='wigslice_833')
                ],
        )
        opt.step(2)
        end_time = time.time()
        print(f"Wiggler correctors set in {end_time - start_time:.2f} seconds.")
        print("Corrector strengths [T]:")
        print(f"  k0l_corr1 = {self.env['k0l_corr1']:.6e}, k0sl_corr1 = {self.env['k0sl_corr1']:.6e}")
        print(f"  k0l_corr2 = {self.env['k0l_corr2']:.6e}, k0sl_corr2 = {self.env['k0sl_corr2']:.6e}")
        print(f"  k0l_corr3 = {self.env['k0l_corr3']:.6e}, k0sl_corr3 = {self.env['k0sl_corr3']:.6e}")
        print(f"  k0l_corr4 = {self.env['k0l_corr4']:.6e}, k0sl_corr4 = {self.env['k0sl_corr4']:.6e}")

    def get_field(self, x, y, s, midpoint=False):
        """
        Vectorized field selector: works with scalar or array s.
        Returns the field as NumPy arrays compatible with xtrack's Boris integrator.
        """

        # Convert to arrays for broadcasting
        x = np.asarray(x)
        y = np.asarray(y)
        s = np.asarray(s)

        # Precompute segment edges
        seg_edges = np.array([seg.s0 for seg in self.segments] +
                             [self.segments[-1].s0 + self.segments[-1].length])

        # Find which segment each s belongs to
        seg_idx = np.searchsorted(seg_edges, s, side="right") - 1
        seg_idx = np.clip(seg_idx, 0, len(self.segments) - 1)

        # Allocate arrays for results
        shape = np.broadcast(x, y, s).shape
        Bx = np.empty(shape)
        By = np.empty(shape)
        Bs = np.empty(shape)

        # Loop only over segments (few), not all s values (many)
        for i, seg in enumerate(self.segments):
            mask = seg_idx == i
            if not np.any(mask):
                continue

            s_loc = s[mask]
            if midpoint:
                s_loc = seg.s0 + 0.5 * seg.length

            # seg.get_field must itself support vectorized x,y,s
            bx, by, bs = seg.get_field(x[mask], y[mask], s_loc)
            Bx[mask], By[mask], Bs[mask] = bx, by, bs

        return Bx, By, Bs

    def get_vector_potential(self, x, y, s):
        """
        Vectorized vector potential selector: supports scalar or array s.
        Returns Ax, Ay, As with same broadcasting shape as (x, y, s).
        """
        x = np.asarray(x)
        y = np.asarray(y)
        s = np.asarray(s)

        # scalar s -> simple lookup (keeps behavior similar to before)
        if s.ndim == 0:
            seg = None
            for seg_candidate in self.segments:
                s0 = seg_candidate.s0
                s1 = s0 + seg_candidate.length
                if s0 <= float(s) <= s1:
                    seg = seg_candidate
                    break
            if seg is None:
                seg = self.segments[-1]
            return seg.get_vector_potential(x, y, s)

        # vectorized path: find segment index per s and compute per-segment
        seg_edges = np.array([seg.s0 for seg in self.segments] +
                             [self.segments[-1].s0 + self.segments[-1].length])
        seg_idx = np.searchsorted(seg_edges, s, side="right") - 1
        seg_idx = np.clip(seg_idx, 0, len(self.segments) - 1)

        shape = np.broadcast(x, y, s).shape
        Ax = np.empty(shape)
        Ay = np.empty(shape)
        As = np.empty(shape)

        for i, seg in enumerate(self.segments):
            mask = seg_idx == i
            if not np.any(mask):
                continue
            s_loc = s[mask]
            Ax_v, Ay_v, As_v = seg.get_vector_potential(x[mask], y[mask], s_loc)
            Ax[mask], Ay[mask], As[mask] = Ax_v, Ay_v, As_v

        return Ax, Ay, As

    def plot_fields(self, x=0.0, y=0.0, n_points=1000, plot_data=False):
        # Define the longitudinal range
        s_start = self.segments[0].s0
        s_end = self.segments[-1].s0 + self.segments[-1].length
        s_vals = np.linspace(s_start, s_end, n_points)

        Bx_vals, By_vals, Bs_vals = [], [], []

        for s in s_vals:
            Bx, By, Bs = self.get_field(x, y, s)
            Bx_vals.append(Bx)
            By_vals.append(By)
            Bs_vals.append(Bs)

        plt.figure(figsize=(10, 5))
        plt.plot(s_vals, Bx_vals, label=r"$B_x$ (bpmeth)")
        plt.plot(s_vals, By_vals, label=r"$B_y$ (bpmeth)")
        plt.plot(s_vals, Bs_vals, label=r"$B_s$ (bpmeth)")

        if plot_data:
            temp_field_fitter = self.field_fitter
            temp_field_fitter.xy_point = (x * 1000, y * 1000)
            temp_field_fitter.select_xy()
            plt.plot(temp_field_fitter.s_full, temp_field_fitter.raw_data[0]['Bx'], label=r"$B_x$ (data)")
            plt.plot(temp_field_fitter.s_full, temp_field_fitter.raw_data[0]['By'], label=r"$B_y$ (data)")
            plt.plot(temp_field_fitter.s_full, temp_field_fitter.raw_data[0]['Bs'], label=r"$B_s$ (data)")

        plt.xlabel("s [m]")
        plt.ylabel("Magnetic field [T]")
        plt.title(f"Wiggler fields along s at x={x:.3f}, y={y:.3f}")
        plt.legend()
        plt.grid(True)
        plt.tight_layout()
        plt.show()

    def plot_vector_potential(self, x=0.0, y=0.0, n_points=1000):
        # Define the longitudinal range
        s_start = self.segments[0].s0
        s_end = self.segments[-1].s0 + self.segments[-1].length
        s_vals = np.linspace(s_start, s_end, n_points)

        Ax_vals, Ay_vals, As_vals = [], [], []

        for s in s_vals:
            Ax, Ay, As = self.get_vector_potential(x, y, s)
            Ax_vals.append(Ax)
            Ay_vals.append(Ay)
            As_vals.append(As)

        plt.figure(figsize=(10, 5))
        plt.plot(s_vals, Ax_vals, label=r"$A_x$")
        plt.plot(s_vals, Ay_vals, label=r"$A_y$")
        plt.plot(s_vals, As_vals, label=r"$A_s$")
        plt.xlabel("s [m]")
        plt.ylabel("Vector Potential [T·m]")
        plt.title(f"Wiggler vector potential along s at x={x:.3f}, y={y:.3f}")
        plt.legend()
        plt.grid(True)
        plt.tight_layout()
        plt.show()