# Compact, refactored Wiggler
# - Less duplication via helpers and component loops
# - Clear ensure() dependency gates
# - Generic sine-fitting used for fields and curvature
# - Small quality-of-life utilities (mid masks, magnitude, plotting core)
#
# Public API preserved (same method names), plus docstrings tightened.

from __future__ import annotations

import numpy as np
import pandas as pd
import scipy as sc
from scipy.signal import find_peaks
from scipy.optimize import curve_fit
from scipy.special import expit
from numpy.polynomial import Polynomial
from dataclasses import dataclass, field
from typing import Dict, Iterable, Tuple, Optional
import matplotlib.pyplot as plt
from scipy.special import expit
from scipy.odr import polynomial


# ================================ Main class ================================

class Wiggler:

    def __init__(
        self,
        file_path,
        xy_point=(0, 0),
        dx=0.001,
        dy=0.001,
        ds=0.001,
        peak_window=(100, 2100),
        n_modes=[3, 3, 3],
        enge_deg = [[15, 15], [15, 15], [15, 15]]
    ):

        self.file_path = file_path
        self.xy_point = xy_point
        self.dx, self.dy, self.ds = dx, dy, ds
        self.peak_window = peak_window

        self.shapes = {
            "Bx": {"n_modes": n_modes[0], "enge_deg_L": enge_deg[0][0], "enge_deg_R": enge_deg[0][1]},
            "By": {"n_modes": n_modes[1], "enge_deg_L": enge_deg[1][0], "enge_deg_R": enge_deg[1][1]},
            "Bs": {"n_modes": n_modes[2], "enge_deg_L": enge_deg[2][0], "enge_deg_R": enge_deg[2][1]},
        }

        self.df = None
        self.s_full = None

        # Dictionary that holds a list of borders for each field
        self.borders_idx = {"Bx": None, "By": None, "Bs": None}

        # Data dictionaries
        # raw_data holds the data from the file
        # fit_data holds the data generated by fitting
        self.raw_data = {"Bx": None, "By": None, "Bs": None}
        self.fit_data = {"Bx": None, "By": None, "Bs": None}

        # Dictionary to hold lists of fitted parameters for each field component
        self.fit_pars = {
            "Bx": {"enge_L": None,"sines" : None , "enge_R": None},
            "By": {"enge_L": None,"sines" : None , "enge_R": None},
            "Bs": {"enge_L": None,"sines" : None , "enge_R": None},
        }

        self.parabola = None
        self.curv_sines = {"x": {}, "y": {}}


    # PUBLIC
    # Setter method that calls all the other methods to arrive at a fit.
    def set(self):
        self._parse_to_dataframe()
        self.select_xy()
        self._find_regions()
        self._fit_sinusoids()

    ####################################################################################################################
    # EVALUATION FUNCTIONS
    ####################################################################################################################

    # PRIVATE
    # This function evaluates a sum of (co)sines at the given x values.
    # The parameters are given as a flat list, where each mode has three parameters:
    #  - Amplitude of the cosine term
    #  - Amplitude of the sine term
    #  - Wave number
    # Thus, for n modes, the parameter list has length 3*n.
    @staticmethod
    def _sinusoid(x, *params):
        # Define the output array
        y = np.zeros_like(x, dtype=np.float64)

        # The range depends on the number of sinusoids there are present in the function.
        # B_x is best approximated with two, whereas B_y only needs one.
        # Note the integer division by 3, because each mode has three parameters.
        for A1, A2, k in zip(params[::3], params[1::3], params[2::3]):
            # General sinusoidal part is a linear combination of cosine and sine.
            # This is equivalent to a single function with a phase-offset, but more numerically stable.
            y += A1 * np.cos(k * x) + A2 * np.sin(k * x)

        return y

    # PRIVATE
    # This function evaluates an Enge function at the given x values.
    # The parameters are given as a list:
    #  - Amplitude
    #  - Coefficients of the polynomial in the exponent, starting from the constant term
    # Thus, for a polynomial of degree n, the parameter list has length n+2
    @staticmethod
    def _enge_function(x, *params):
        amp = params[0]
        poly = np.polynomial.Polynomial(params[1:])
        return amp * expit(-poly(x))



    ####################################################################################################################
    # IDENTIFYING REGIONS AND SETTING BORDERS IN DATA CLASSES
    ####################################################################################################################

    # PRIVATE
    # This method reads the data from the file and stores it in a pandas DataFrame.
    def _parse_to_dataframe(self) -> None:
        df = pd.read_csv(
            self.file_path, sep=r"\s+", header=None, names=["X", "Y", "Z", "Bx", "By", "Bs"]
        )
        df.set_index(["X", "Y", "Z"], inplace=True)
        self.df = df

    # PUBLIC
    # This method selects the data at the specified (x,y) point and stores it in the fields dictionary.
    # It is made public so that the user can change the (x,y) point and re-select the data without re-parsing the file.
    def select_xy(self):
        subset = self.df.xs(self.xy_point, level=["X", "Y"]).sort_index()

        # Sets the horizontal axis and scales it to meters.
        self.s_full = subset.index.to_numpy() * self.ds

        # Store the raw data for each field.
        self.raw_data["Bx"] = subset["Bx"].to_numpy()
        self.raw_data["By"] = subset["By"].to_numpy()
        self.raw_data["Bs"] = subset["Bs"].to_numpy()

        # Now that the raw data is stored, we can initialize the fit_data arrays.
        self.fit_data["Bx"] = np.zeros_like(self.raw_data["Bx"])
        self.fit_data["By"] = np.zeros_like(self.raw_data["By"])
        self.fit_data["Bs"] = np.zeros_like(self.raw_data["Bs"])

    # PRIVATE
    # This method first finds the peaks and valleys in the data for Bx and By
    # Then, it combines them into one array for the extrema of Bx and By
    # Finally, it sets the borders_idx attribute of the FieldChannel objects for Bx and By
    def _find_regions(self):
        w_left = self.peak_window[0]
        w_right = self.peak_window[1]

        for field in ["Bx", "By", "Bs"]:
            field_peaks = find_peaks(self.raw_data[field])[0]
            field_valleys = find_peaks(-self.raw_data[field])[0]
            field_peaks = field_peaks[np.logical_and(field_peaks > w_left, field_peaks < w_right)]
            field_valleys = field_valleys[np.logical_and(field_valleys > w_left, field_valleys < w_right)]
            field_extrema = np.sort(np.concatenate((field_peaks, field_valleys)))
            self.borders_idx[field] = [field_extrema[1], field_extrema[-2]]



    ####################################################################################################################
    # SINUSOID FITTING
    ####################################################################################################################

    # PRIVATE
    # This function finds the amplitudes and frequencies of the (co)sines present in the data.
    @staticmethod
    def _find_modes(x, y, dx, n_modes):
        # Fourier Transform and frequencies
        fft = sc.fft.fft(y)
        fftfreq = sc.fft.fftfreq(len(x), dx)

        # Only keep positive frequencies
        fft = fft[fftfreq > 0]
        fftfreq = fftfreq[fftfreq > 0]

        # Find peaks in the magnitude spectrum
        peaks = find_peaks(np.abs(fft))[0]

        # Order peaks by magnitude, descending
        order = np.argsort(np.abs(fft[peaks]))[::-1]
        peaks = peaks[order][:n_modes]

        # Extract amplitudes and frequencies in the same order
        amplitudes = fft[peaks]
        cos_amps = 2 * dx * amplitudes.real
        sin_amps = -2 * dx * amplitudes.imag
        k_values = 2 * np.pi * fftfreq[peaks]

        return cos_amps, sin_amps, k_values

    # PRIVATE
    # This method fits sinusoids to the data in the regions defined by borders_idx.
    # The fitted parameters are stored in the fit_pars attribute.
    # The fitted data is stored in the fit_data attribute.
    # It uses the _find_modes function to get initial guesses for the parameters.
    def _fit_sinusoids(self):
        for field in ["Bx", "By", "Bs"]:
            idx = self.borders_idx[field]
            s_reg = self.s_full[idx[0]:idx[1]]
            field_reg = self.raw_data[field][idx[0]:idx[1]]
            n_modes = self.shapes[field]["n_modes"]

            cos_amps, sin_amps, k_modes = self._find_modes(s_reg, field_reg, self.ds, n_modes)

            p0 = np.zeros(n_modes*3)

            for ii in range(n_modes):
                p0[3 * ii] = cos_amps[ii]
                p0[3 * ii + 1] = sin_amps[ii]
                p0[3 * ii + 2] = k_modes[ii]

            popt, pcov = curve_fit(self._sinusoid, s_reg, field_reg, p0=p0)

            self.fit_pars[field]["sines"] = popt
            self.fit_data[field][idx[0]:idx[1]] = self._sinusoid(s_reg, *popt)



    ####################################################################################################################
    # ENGE FITTING
    ####################################################################################################################

    # PRIVATE
    # This method:
    #  - rescales x to lie between -1 and 1
    #  - shifts y to be positive
    @staticmethod
    def _rescale_xy(x, y):
        x = (x - np.min(x)) / (np.max(x) - np.min(x)) * 2 - 1
        if np.min(y) <= 0:
            y -= np.min(y) - 0.1
        return x, y

    # PRIVATE
    # This method rescales the polynomial coefficients after fitting.
    @staticmethod
    def _rescale_poly_coeffs(c_u, x_max, x_min):
        p_u = Polynomial(c_u)
        delta = x_max - x_min
        avg   = (x_max + x_min) / 2
        x   = Polynomial([avg, delta/2])
        p_x = p_u(x)
        return p_x.coef

    # PRIVATE
    @staticmethod
    def _fit_polynomial(x, y, A, deg):
        t = np.log(A / y - 1)  # transformed targets
        coeffs = np.polyfit(x, t, deg)  # monomial basis
        return np.poly1d(coeffs)

    # PRIVATE
    def _error_for_A(self, A, x, y, deg):
        poly = self._fit_polynomial(x, y, A, deg=deg)
        params = [A] + list(poly.coef)
        y_hat = self._enge_function(x, *params)
        return np.sum((y - y_hat) ** 2)

    def _enge_fit(self, x, y, deg):
        x_scaled, y_scaled = self._rescale_xy(x, y)
        A_guess = np.linspace(max(y) * 1.01, 10, 50)
        res = sc.optimize.minimize_scalar(self._error_for_A, bounds=(A_guess[0], A_guess[-1]), args=(x_scaled, y_scaled, deg), method="bounded")
        A_opt = res.x
        poly = self._fit_polynomial(x_scaled, y_scaled, A_opt, deg=deg)
        params = [A_opt] + list(poly.coef)
        params[1:] = self._rescale_poly_coeffs(params[1:], np.max(x), np.min(x))
        return params


    ####################################################################################################################
    # PLOTTING
    ####################################################################################################################

    # PUBLIC
    # Plot the data against the fit.
    def plot_fields(self):
        fig1, (ax1, ax2, ax3) = plt.subplots(3, figsize=(10, 4), constrained_layout=True)
        ax1.plot(self.s_full, self.raw_data["Bx"])
        ax1.plot(self.s_full, self.fit_data["Bx"])
        ax2.plot(self.s_full, self.raw_data["By"])
        ax2.plot(self.s_full, self.fit_data["By"])
        ax3.plot(self.s_full, self.raw_data["Bs"])
        ax3.plot(self.s_full, self.fit_data["Bs"])

        # Add vertical lines at different positions for each subplot
        ax1.axvline(x=self.s_full[self.borders_idx["Bx"][0]], color='k', linestyle='--', linewidth=1)
        ax1.axvline(x=self.s_full[self.borders_idx["Bx"][1]], color='k', linestyle='--', linewidth=1)
        ax2.axvline(x=self.s_full[self.borders_idx["By"][0]], color='k', linestyle='--', linewidth=1)
        ax2.axvline(x=self.s_full[self.borders_idx["By"][1]], color='k', linestyle='--', linewidth=1)

        # Label the graphs.
        ax1.set_title(f"Magnetic Field at (X, Y) = {self.xy_point}")
        ax2.set_xlabel("Longitudinal Position, $s$, [m]")
        ax1.set_ylabel("Horizontal Field, $B_x$, [T]")
        ax2.set_ylabel("Vertical Field, $B_y$, [T]")
        ax3.set_ylabel("Longitudinal Field, $B_s$, [T]")

        # Make a legend.
        ax1.legend(["$B_x$ Data", "$B_x$ Fit"], loc="lower right")
        ax2.legend(["$B_y$ Data", "$B_y$ Fit"], loc="lower right")
        ax3.legend(["$B_s$ Data", "$B_s$ Fit"], loc="upper right")

        # Turn on the grids.
        ax1.grid()
        ax2.grid()
        ax3.grid()

        plt.show()